apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-api
  template:
    metadata:
      labels:
        app: bank-api
    spec:
      containers:
      - name: bank-api
        image: us-central1-docker.pkg.dev/molten-unison-462818-r2/bank-app-repo-gke-test/bank-api-gke
       #image: gcr.io/molten-unison-462818-r2/bank-api-gke
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: bank-api-service
spec:
  selector:
    app: bank-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer

